export default {
  borders: {
    borderRadius: {
      large: '0.25rem',
      medium: '0.125rem',
      small: '0.0625rem',
      xLarge: '0.5rem',
    },
    borderSize: {
      large: '0.25rem',
      medium: '0.125rem',
      small: '0.0625rem',
      xLarge: '0.5rem',
    },
  },
  colors: {
    accent1: '#d8d8d8',
    accent2: '#828282',
    accent3: '#666666',
    black: '#000',
    danger: '#f44336',
    dark: '#4D4D4D',
    info: '#90caf9',
    light: '#CCCCCC',
    medium: '#999999',
    primary: '#3F51B5',
    secondary: '#90a4ae',
    success: '#8bc34a',
    warning: '#ff9800',
    white: '#fff',
  },
  icons: {
    iconLarge: '3.75rem',
    iconMedium: '3rem',
    iconSmall: '2.125rem',
    iconXLarge: '6rem',
  },
  spacing: {
    large: {
      desktopSpacing: '1.5rem',
      mobileSpacing: '1rem',
      tabletLandscapeSpacing: '1.5rem',
      tabletPortraitSpacing: '1rem',
    },
    medium: {
      desktopSpacing: '1rem',
      mobileSpacing: '0.5rem',
      tabletLandscapeSpacing: '1rem',
      tabletPortraitSpacing: '0.5rem',
    },
    small: {
      desktopSpacing: '0.5rem',
      mobileSpacing: '0.25rem',
      tabletLandscapeSpacing: '0.5rem',
      tabletPortraitSpacing: '0.25rem',
    },
    xLarge: {
      desktopSpacing: '2rem',
      mobileSpacing: '1.5rem',
      tabletLandscapeSpacing: '2rem',
      tabletPortraitSpacing: '1.5rem',
    },
  },
  typography: {
    body1: {
      color: '#000000',
      desktopSize: '1rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '0.875rem',
      tabletLandscapeSize: '1rem',
      tabletPortraitSize: '1rem',
      textTransform: 'inherit',
    },
    body2: {
      color: '#000000',
      desktopSize: '0.875rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '0.75rem',
      tabletLandscapeSize: '0.875rem',
      tabletPortraitSize: '0.875rem',
      textTransform: 'inherit',
    },
    button: {
      color: '#ffffff',
      desktopSize: '0.875rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: 'normal',
      mobileSize: '0.875rem',
      tabletLandscapeSize: '0.875rem',
      tabletPortraitSize: '0.875rem',
      textTransform: 'uppercase',
    },
    caption1: {
      color: '#000000',
      desktopSize: '0.75rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '0.75rem',
      tabletLandscapeSize: '0.75rem',
      tabletPortraitSize: '0.75rem',
      textTransform: 'inherit',
    },
    caption2: {
      color: '#000000',
      desktopSize: '0.625rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '0.625rem',
      tabletLandscapeSize: '0.625rem',
      tabletPortraitSize: '0.625rem',
      textTransform: 'inherit',
    },
    subtitle1: {
      color: '#000000',
      desktopSize: '1rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '0.875rem',
      tabletLandscapeSize: '1rem',
      tabletPortraitSize: '1rem',
      textTransform: 'inherit',
    },
    subtitle2: {
      color: '#000000',
      desktopSize: '0.875rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: 'normal',
      mobileSize: '0.75rem',
      tabletLandscapeSize: '0.875rem',
      tabletPortraitSize: '0.875rem',
      textTransform: 'inherit',
    },
    title1: {
      color: '#000000',
      desktopSize: '6rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '300',
      letterSpacing: 'normal',
      mobileSize: '3.5625rem',
      tabletLandscapeSize: '6.625rem',
      tabletPortraitSize: '4.6875rem',
      textTransform: 'inherit',
    },
    title2: {
      color: '#000000',
      desktopSize: '3.75rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '300',
      letterSpacing: 'normal',
      mobileSize: '2.4375rem',
      tabletLandscapeSize: '3.25rem',
      tabletPortraitSize: '3.25rem',
      textTransform: 'inherit',
    },
    title3: {
      color: '#000000',
      desktopSize: '3rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '1.6875rem',
      tabletLandscapeSize: '2.75rem',
      tabletPortraitSize: '2.5rem',
      textTransform: 'inherit',
    },
    title4: {
      color: '#000000',
      desktopSize: '2.125rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '1.25rem',
      tabletLandscapeSize: '1.625rem',
      tabletPortraitSize: '1.625rem',
      textTransform: 'inherit',
    },
    title5: {
      color: '#000000',
      desktopSize: '1.5rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '400',
      letterSpacing: 'normal',
      mobileSize: '1.125rem',
      tabletLandscapeSize: '1.375rem',
      tabletPortraitSize: '1.25rem',
      textTransform: 'inherit',
    },
    title6: {
      color: '#000000',
      desktopSize: '1.25rem',
      fontFamily: 'Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: 'normal',
      mobileSize: '1rem',
      tabletLandscapeSize: '1.125rem',
      tabletPortraitSize: '1.125rem',
      textTransform: 'inherit',
    },
  },
};
