export const MAX_ACTIONS = 5;
export const MAX_VARIABLES = 20;
export const MAX_INTERACTIONS = 20;
export const MAX_ACTION_EVENTS = 50;

export const ICONS = [
  'AccordionIcon',
  'AccordionItemIcon',
  'AlertIcon',
  'AutoCompleteIcon',
  'AvatarIcon',
  'BreadcrumbIcon',
  'BreadcrumbItemIcon',
  'ButtonGroupIcon',
  'ButtonIcon',
  'CardIcon',
  'CardActionsIcon',
  'CardContentIcon',
  'CardHeaderIcon',
  'CardMediaIcon',
  'CheckboxIcon',
  'CheckboxGroupIcon',
  'ChipIcon',
  'Column2Icon',
  'Column3Icon',
  'ColumnIcon',
  'ConditionalIcon',
  'ContainerIcon',
  'CreateFormIcon',
  'DataContainer',
  'DataList',
  'DataTable',
  'DataTableBody',
  'DataTableColumn',
  'DataTableHead',
  'DataTableRow',
  'DatePickerIcon',
  'DateTimePickerIcon',
  'DecimalInputIcon',
  'DefinitionListIcon',
  'DeleteRecordIcon',
  'DialogIcon',
  'DrawerIcon',
  'DynamicFormIcon',
  'DynamicTableIcon',
  'DynamicTilesIcon',
  'EmailInputIcon',
  'FileInputIcon',
  'FormIcon',
  'GridIcon',
  'HiddenInputIcon',
  'HorizontalRuleIcon',
  'HtmlIcon',
  'IbanInputIcon',
  'IconIcon',
  'ImageIcon',
  'ImageInputIcon',
  'IncludeIcon',
  'LabelIcon',
  'Layout1Icon',
  'Layout2Icon',
  'Layout363Icon',
  'Layout444Icon',
  'Layout48Icon',
  'Layout66Icon',
  'Layout3333Icon',
  'Layout84Icon',
  'ListItemIcon',
  'ListWithDataIcon',
  'LoginFormIcon',
  'MenuIcon',
  'MenuItemIcon',
  'MultiLineIcon',
  'MultiSelectIcon',
  'NavbarIcon',
  'NavItemIcon',
  'NavSidebarIcon',
  'NumberInputIcon',
  'OrderedListIcon',
  'PanelIcon',
  'PaperIcon',
  'ParagraphIcon',
  'PasswordInputIcon',
  'PhoneInputIcon',
  'PriceInputIcon',
  'ProgressBarIcon',
  'RadioButtonIcon',
  'RowIcon',
  'RowColumnIcon',
  'SelectIcon',
  'SidebarLeftIcon',
  'SnackbarIcon',
  'StepIcon',
  'StepperIcon',
  'SubmitButtonIcon',
  'SwitchIcon',
  'TabIcon',
  'TabsIcon',
  'Table',
  'TextareaIcon',
  'TextInputIcon',
  'TimePickerIcon',
  'TitleIcon',
  'UnorderedListIcon',
  'UpdateFormIcon',
  'UrlInputIcon',
];

export const OPTIONS = [
  'ACTION',
  'ACTION_INPUT',
  'ACTION_INPUT_OBJECTS',
  'ACTION_PROPERTIES',
  'AUTHENTICATION_PROFILE',
  'BUTTONGROUP',
  'COLOR',
  'CUSTOM',
  'CUSTOM_MODEL_ATTRIBUTE',
  'DROPDOWN',
  'ENDPOINT',
  'FILTER',
  'FONT',
  'FORM_DATA',
  'MODEL',
  'MODELS',
  'NUMBER',
  'PROPERTY',
  'PROPERTIES',
  'SIZE',
  'SIZES',
  'TEXT',
  'THEME',
  'TOGGLE',
  'UNIT',
  'VARIABLE',
];

export const CONDITION_TYPE = ['HIDE', 'SHOW'];
export const COMPARATORS = ['EQ'];
export const MODAL_TYPE = ['MODEL_AND_PROPERTIES'];

export const CONFIGURATION_AS = [
  'BUTTONGROUP',
  'DROPDOWN',
  'MULTILINE',
  'UNIT',
  'VISIBILITY',
];

export const INTERACTION_TYPE = ['Global', 'Custom'];

export const EVENT_KIND_NEW_RUNTIME = 'authenticate_user';

export const EVENT_KIND = [
  'action',
  'assign',
  'auto_increment_generate',
  'auto_increment_set',
  'condition',
  'create',
  'create_betty_user',
  'delete',
  'export',
  'expression',
  'group',
  'http_request',
  'import',
  'login_web_user',
  'logout_web_user',
  'loop',
  'pdf_generate',
  'pdf_merge',
  'redirect_web_page',
  'render_web_template',
  'send_mail',
  'sftp_download',
  'sftp_list',
  'sftp_upload',
  'update',
  'zip',
];

export const VARIABLE_KIND = ['construct', 'object', 'string', 'integer'];
