name: CI
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19
      - run: bun install --frozen-lockfile
      - name: Commit lint
        run: bun commitlint --from $(git rev-parse --short HEAD^1) --to $(git rev-parse --short HEAD^2)
      - name: Run prettier
        run: bun run fix
      - name: Run build
        run: bun run build
      - name: Run linting
        run: bun run lint
      - name: Run tests
        run: bun test
