name: CI
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.2
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.2'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Commit lint
        run: yarn commitlint --from $(git rev-parse --short HEAD^1) --to $(git rev-parse --short HEAD^2)
      - name: Run prettier
        run: yarn prettier:write
      - name: Run build
        run: yarn build
      - name: Run linting
        run: yarn lint
      - name: Run tests
        run: yarn test
