name: Release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.0.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.0.0'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build && npx semantic-release
