name: Release
on:
  push:
    branches:
      - master
      - beta
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build CLI
        run: bun run build
      - name: Run tests
        run: bun run test
      - name: Release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun semantic-release
